export const expertSystemEndpoints = {
    expsys: {
        subjects: {
            allsubjects: '/expsys_module/subjects-all/',
            create: '/expsys_module/subject-create/',
            delete_subject: '/expsys_module/delete-subject/{id}/',
            create_competencies: '/expsys_module/competence-create/',
            create_indicator: '/expsys_module/indicator-create/',
            allcompenencies: '/expsys_module/subjectsindicators/',
            competencies: '/expsys_module/allcompetencies',
            countsubjectsind: '/expsys_module/indicator-subjects-count',
            indicators: '/expsys_module/allindicators',
            indicatorscompenencies: '/expsys_module/competenceindicators/',
            delete_competence: '/expsys_module/delete-competence/{id}/',
            delete_indicator: '/expsys_module/delete-indicator/{id}/',
            information: '/expsys_module/information-competence/',
            update_subject: '/expsys_module/update-subject/{id}/',
            update_competence: '/expsys_module/update-competence/{id}/',
            update_indicator: '/expsys_module/update-indicator/{id}/',
            countsstudents: '/expsys_module/countstudents-subject/',
            countslessons: '/expsys_module/countlessons-subject/',
            countstests: '/expsys_module/counttests-subject/',
        },
    },
    expert_system: {
        studyGroups: 'expert_system/study-groups/',
        students: 'expert_system/students/',
        studentsMe: 'expert_system/students/me/',
        companies: 'expert_system/companies/',
        companiesMe: 'expert_system/companies/me/',
        skills: 'expert_system/skills/',
        userSkills: 'expert_system/user-skills/',
        myVacancies: 'expert_system/companies/my-vacancies/',
        roles: 'expert_system/roles/',
        trajectorySteps: 'expert_system/trajectory-steps/',
        orientationTests: 'expert_system/orientation-tests/',
        orientationQuestions: 'expert_system/orientation-questions/',
        orientationAnswers: 'expert_system/orientation-answers/',
        orientationResults: 'expert_system/orientation-results/',
        orientationUserAnswers: 'expert_system/orientation-user-answers/',

        skillTests: 'expert_system/skill-tests/',
        skillQuestions: 'expert_system/skill-questions/',
        skillAnswers: 'expert_system/skill-answers/',
        testResults: 'expert_system/test-results/',

        vacancies: 'expert_system/vacancies/',
        vacancySkills: 'expert_system/vacancy-skills/',
        applications: 'expert_system/applications/',

        setUserSkillTest: 'expert_system/set-user-skill-test',
        getUserSkillTest: 'expert_system/get-user-skill-tests',
        getUserSkills: 'expert_system/get-user-skills',
        setUserSkills: 'expert_system/set-user-skills',

        getAllTests: 'expert_system/get-all-tests',
        createTest: 'expert_system/create-test',
        deleteTest: 'expert_system/delete-test',
        getTest: 'expert_system/get-test',
        updateTest: 'expert_system/patch-test',
        getSkillsForCreate: 'expert_system/get-skills-for-create-test',
        getSkillsForRedact: 'expert_system/get-skills-for-redact-test',
        getTestIdBySkill: 'expert_system/get-test-id-by-skill',
        getTestForRedact: 'expert_system/get-test-for-redact',
        evaluateTest: 'expert_system/evaluate-test',
        saveOrientationTestResult: 'expert_system/orientation-test-results/',
        saveBestRoleToStudent: 'expert_system/students/me/set-role/',
        setStudentRole: 'expert_system/students/me/set-role/',
        getTestResult: 'expert_system/get-test-result',
        courses: 'expert_system/courses/',
        getTestResultBySkillId: 'expert_system/get-test-result-by-skill-id',
        deleteTestResultBySkill: 'expert_system/delete-test-result-by-skill',
        analytics: {
            systemMetrics: 'expert_system/analytics/system-metrics/',
            skillsData: 'expert_system/analytics/skills-data/',
            topSkills: 'expert_system/analytics/top-skills/',
            studentsStats: 'expert_system/analytics/students-stats/',
            testingData: 'expert_system/analytics/testing-data/',
        }
    }
};

