export const endpoints = {
  auth: {
    login: 'cms/adp/authorization/',
    validateRegistration: 'cms/adp/validate_registration/',
    sendCode: 'cms/adp/send_code/',
    verifyCode: 'cms/adp/verify_code/',
    registration: 'cms/adp/registration/',
    protected: 'cms/adp/protected/',
  },
  cms: {
        checkAccessToPage: 'cms/check_access_to_page/',
        checkAccessToComponent: 'cms/check_access_to_component/',
        checkAccessToAdminPanel: 'cms/check_access_to_admin_panel/',
        
        addGroupCategory: 'cms/post_group_category/',
        changeGroupCategory: 'cms/change_group_category/',
        deleteGroupCategory: 'cms/delete_group_category/',
        getGroupCategories: 'cms/get_group_categories/',
        
        addGroup: 'cms/add_group/',
        deleteGroup: 'cms/delete_group/',
        getGroups: 'cms/get_groups/',
        changeGroup: 'cms/change_group/',

        addPermission: 'cms/add_permission/',
        deletePermission: 'cms/delete_permission/',
        changePermission: 'cms/change_permission/',
        getPermissions: 'cms/get_permissions/',

        addUserPermission: 'cms/add_user_permission/',
        removeUserPermission: 'cms/remove_user_permission/',
        addUserGroup: 'cms/add_user_group/',
        removeUserGroup: 'cms/remove_user_group/',
        getUserGroupsAndPermissions: 'cms/get_user_groups_and_permissions/',
        getUserGroups: 'cms/get_user_groups/',
        getUserPermissions: 'cms/get_user_permissions/',

        addGroupsPermissions: 'cms/add_groups_permissions/',
        removeGroupsPermissions: 'cms/remove_groups_permissions/',
        getPermissionsByCategory: 'cms/get_permissions_by_category/',
        getUserName: 'cms/get_user_name/',
    },
    expert_system: {
        studyGroups: 'expert_system/study-groups/',
        students: 'expert_system/students/',
        studentsMe: 'expert_system/students/me/',
        companies: 'expert_system/companies/',
        companiesMe: 'expert_system/companies/me/',
        skills: 'expert_system/skills/',
        userSkills: 'expert_system/user-skills/',
        roles: 'expert_system/roles/',
        trajectorySteps: 'expert_system/trajectory-steps/',
        orientationTests: 'expert_system/orientation-tests/',
        orientationQuestions: 'expert_system/orientation-questions/',
        orientationAnswers: 'expert_system/orientation-answers/',
        skillTests: 'expert_system/skill-tests/',
        skillQuestions: 'expert_system/skill-questions/',
        skillAnswers: 'expert_system/skill-answers/',
        testResults: 'expert_system/test-results/',
        vacancies: 'expert_system/vacancies/',
        vacancySkills: 'expert_system/vacancy-skills/',
        applications: 'expert_system/applications/',
        orientationResults: 'expert_system/orientation-results/',
        orientationUserAnswers: 'expert_system/orientation-answers/',
        setUserSkillTest: 'expert_system/set-user-skill-test',
        getUserSkillTest: 'expert_system/get-user-skill-tests',
        getUserSkills: 'expert_system/get-user-skills'
  },
  bi: {
        DatasetsList: 'bi_analysis/bi_datasets/',
        ConnectionsList: 'bi_analysis/bi_connections/',
        CheckConnection: 'bi_analysis/bi_connections/check-connection/',
        ChartsList: 'bi_analysis/bi_charts/',
        Upload: 'bi_analysis/bi_datasets/upload/',
        UploadedFiles: 'bi_analysis/bi_datasets/user-files/',
  },
  shortcodes: {
    templates: 'cms_shortcodes/templates/',
    pages: 'cms_shortcodes/pages/',
    instances: 'cms_shortcodes/instances/',
    categories: 'cms_shortcodes/categories/',
  },
  learning_analytics: {
      tables: 'learning_analytics/tables/',
      clearTables: 'learning_analytics/tables/clear/',

      excel: {
          upload: 'learning_analytics/data_formalization_submodule/upload-excel/',
          process: 'learning_analytics/data_formalization_submodule/process-excel/'
      },

      relations: {
          disciplineTechnology: 'learning_analytics/data_formalization_submodule/relations/discipline-technology/',
          disciplineCompetency: 'learning_analytics/data_formalization_submodule/relations/discipline-competency/',
          vacancyTechnology: 'learning_analytics/data_formalization_submodule/relations/vacancy-technology/',
          vacancyCompetency: 'learning_analytics/data_formalization_submodule/relations/vacancy-competency/',
          vcmTechnology: 'learning_analytics/data_formalization_submodule/relations/vcm-technology/',
          vcmCompetency: 'learning_analytics/data_formalization_submodule/relations/vcm-competency/',
      },

      employers: {
          get: 'learning_analytics/employers/',
          create: 'learning_analytics/employers/',
          update: (pk) => `learning_analytics/employers/${pk}/`,
          delete: (pk) => `learning_analytics/employers/${pk}/`,
          loadSampleData: 'learning_analytics/employers/loadsampledata/',
      },

      specialities: {
          get: 'learning_analytics/data_formalization_submodule/specialities/',
          create: 'learning_analytics/data_formalization_submodule/specialities/',
          update: (pk) => `learning_analytics/data_formalization_submodule/specialities/${pk}/`,
          delete: (pk) => `learning_analytics/data_formalization_submodule/specialities/${pk}/`,
          loadSampleData: 'learning_analytics/data_formalization_submodule/specialities/loadsampledata/',
      },
      curriculums: {
          get: 'learning_analytics/data_formalization_submodule/curriculums/',
          create: 'learning_analytics/data_formalization_submodule/curriculums/',
          update: (pk) => `learning_analytics/data_formalization_submodule/curriculums/${pk}/`,
          delete: (pk) => `learning_analytics/data_formalization_submodule/curriculums/${pk}/`,
          loadSampleData: 'learning_analytics/data_formalization_submodule/curriculums/loadsampledata/',
      },
      technologies: {
          get: 'learning_analytics/data_formalization_submodule/technologies/',
          create: 'learning_analytics/data_formalization_submodule/technologies/',
          update: (pk) => `learning_analytics/data_formalization_submodule/technologies/${pk}/`,
          delete: (pk) => `learning_analytics/data_formalization_submodule/technologies/${pk}/`,
          loadSampleData: 'learning_analytics/data_formalization_submodule/technologies/loadsampledata/',
      },
      competencies: {
          get: 'learning_analytics/data_formalization_submodule/competencies/',
          create: 'learning_analytics/data_formalization_submodule/competencies/',
          update: (pk) => `learning_analytics/data_formalization_submodule/competencies/${pk}/`,
          delete: (pk) => `learning_analytics/data_formalization_submodule/competencies/${pk}/`,
          loadSampleData: 'learning_analytics/data_formalization_submodule/competencies/loadsampledata/',
      },
      baseDisciplines: {
          get: 'learning_analytics/data_formalization_submodule/base_disciplines/',
          create: 'learning_analytics/data_formalization_submodule/base_disciplines/',
          update: (pk) => `learning_analytics/data_formalization_submodule/base_disciplines/${pk}/`,
          delete: (pk) => `learning_analytics/data_formalization_submodule/base_disciplines/${pk}/`,
          loadSampleData: 'learning_analytics/data_formalization_submodule/base_disciplines/loadsampledata/',
      },
      disciplines: {
          get: 'learning_analytics/data_formalization_submodule/disciplines/',
          create: 'learning_analytics/data_formalization_submodule/disciplines/',
          update: (pk) => `learning_analytics/data_formalization_submodule/disciplines/${pk}/`,
          delete: (pk) => `learning_analytics/data_formalization_submodule/disciplines/${pk}/`,
          loadSampleData: 'learning_analytics/data_formalization_submodule/disciplines/loadsampledata/',
      },
      vacancies: {
          get: 'learning_analytics/data_formalization_submodule/vacancies/',
          create: 'learning_analytics/data_formalization_submodule/vacancies/',
          update: (pk) => `learning_analytics/data_formalization_submodule/vacancies/${pk}/`,
          delete: (pk) => `learning_analytics/data_formalization_submodule/vacancies/${pk}/`,
          loadSampleData: 'learning_analytics/data_formalization_submodule/vacancies/loadsampledata/',
      },
      acms: {
          get: 'learning_analytics/data_formalization_submodule/acms/',
          create: 'learning_analytics/data_formalization_submodule/acms/',
          update: (pk) => `learning_analytics/data_formalization_submodule/acms/${pk}/`,
          delete: (pk) => `learning_analytics/data_formalization_submodule/acms/${pk}/`,
          loadSampleData: 'learning_analytics/data_formalization_submodule/acms/loadsampledata/',
      },
      vcms: {
          get: 'learning_analytics/data_formalization_submodule/vcms/',
          create: 'learning_analytics/data_formalization_submodule/vcms/',
          update: (pk) => `learning_analytics/data_formalization_submodule/vcms/${pk}/`,
          delete: (pk) => `learning_analytics/data_formalization_submodule/vcms/${pk}/`,
          loadSampleData: 'learning_analytics/data_formalization_submodule/vcms/loadsampledata/',
      },
      ucms: {
          get: 'learning_analytics/data_formalization_submodule/ucms/',
          create: 'learning_analytics/data_formalization_submodule/ucms/',
          update: (pk) => `learning_analytics/data_formalization_submodule/ucms/${pk}/`,
          delete: (pk) => `learning_analytics/data_formalization_submodule/ucms/${pk}/`,
          loadSampleData: 'learning_analytics/data_formalization_submodule/ucms/loadsampledata/',
      },
      importHistory: {
          get: 'learning_analytics/data_formalization_submodule/import_history/',
          create: 'learning_analytics/data_formalization_submodule/import_history/',
          update: (pk) => `learning_analytics/data_formalization_submodule/import_history/${pk}/`,
          delete: (pk) => `learning_analytics/data_formalization_submodule/import_history/${pk}/`,
      },
      importStats: {
          get: 'learning_analytics/data_formalization_submodule/import_stats/',
          update: (pk) => `learning_analytics/data_formalization_submodule/import_stats/${pk}/`,
      },
  },
};